# Generated by Django 4.2.1 on 2023-05-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('hotel', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('hotel', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
                ('people_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
